### ISSUE TITLE
How to train/create control codes?

### ISSUE THREAD

**Issue by nullphantom** [salesforce/ctrl#19] opened 2019-09-19 12:51 UTC
Hi. I am thinking about to train my own control codes. How it is possible?

**Comment by GrahamboJangles** [comment] 2019-09-20 05:53
The FAQ answers this:

Q: Will you be releasing the training code and data?
A: We plan to release the training code soon. We will not be releasing the training data, but we will release tips and scripts related to data collection.

**Comment by keskarnitish** [comment] 2019-09-20 16:43
Closing this since it's a duplicate of https://github.com/salesforce/ctrl/issues/8

I'll be adding some discussions there.

**Closed by keskarnitish** 2019-09-20 16:43 UTC
