### ISSUE TITLE
more than 600 labels

### ISSUE THREAD

**Issue by leejason** [salesforce/ctrl#45] opened 2019-10-17 09:34 UTC
What if the number of multiple labels is 600+? Can the advised "replication" of training data still be a viable option? Is there any better way without lots of duplicated records for different labels? 

> It's up to you really; it depends on what you want to do at the end. 
> If it is a hierarchy (like, [Books, Author, Title]), then you don't need to replicate the data. 
> If it is a label for the data but the data has multiple labels (like, Wikipedia Stoicism is ... and > Philosophy Stoicism is..), then you probably would benefit from the replication. 

_Originally posted by @keskarnitish in https://github.com/salesforce/ctrl/issues/35#issuecomment-542315438_

**Comment by keskarnitish** [comment] 2019-10-23 16:54
Seems to be a duplicate of https://github.com/salesforce/ctrl/issues/37 and has been addressed. Reopen that thread if necessary.

**Closed by keskarnitish** 2019-10-23 16:54 UTC
